//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public Item()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int Id { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime updated_at { get; set; }
        public int SupplierId { get; set; }
        public string item_name { get; set; }
        public double price { get; set; }
        public int SupplierId1 { get; set; }
        public int StockId { get; set; }
    
        public virtual Supplier Supplier { get; set; }
        public virtual Stock Stock { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
    }
}
